name: 'digilab'

# Exposed ports
#

# postgrest: 3000
# postgres:  5333
# nginx:     7070
# swagger:   8080
# pgadmin:   8888

services:

  postgres:
    image: 'postgres:15-alpine'
    restart: always
    ports:
      - "5333:5432"
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${DIGILAB_PASSWORD}
    volumes:
      - postgres-data:/var/lib/postgresql/data/
    healthcheck:
      # the -U user has to match the POSTGRES_USER value
      test: ["CMD-SHELL", "pg_isready -U digilab"]
      interval: 5s
      timeout: 5s
      retries: 30

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    ports:
      - "8888:8888"
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${DIGILAB_PASSWORD}
      PGADMIN_LISTEN_PORT: 8888
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    depends_on:
      postgres:
        condition: service_healthy

  postgrest:
    image: postgrest/postgrest
    restart: always
    ports:
      - "3000:3000"
    environment:
      PGRST_DB_URI: postgres://${POSTGRES_USER}:${DIGILAB_PASSWORD}@postgres:5432/${POSTGRES_DB}
      PGRST_DB_SCHEMA: ${DB_SCHEMA}
      PGRST_DB_ANON_ROLE: ${DB_ANON_ROLE}
      PGRST_OPENAPI_SERVER_PROXY_URI: ${API_URL}
      PGRST_SERVER_PORT: 3000
    depends_on:
      postgres:
        condition: service_healthy

  swagger:
    image: swaggerapi/swagger-ui
    restart: always
    ports:
      - "8080:8080"
    environment:
      API_URL: ${API_URL}
    depends_on:
      - postgrest

  nginx:
    image: nginx:mainline-alpine
    restart: unless-stopped
    ports:
      - "7070:7070"
    volumes:
      - "./html:/usr/share/nginx/html"
      - "./nginx.conf:/etc/nginx/conf.d/default.conf"
    depends_on:
      - postgrest

networks:
  default:
    name: digilab

volumes:
  postgres-data:
  pgadmin-data:

